<?php
/**
 * @file
 * footer_browser_library.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function footer_browser_library_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-browse-library_audio--video:<front>
  $menu_links['menu-browse-library_audio--video:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Audio & Video',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_audio--video:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_books--authors:<front>
  $menu_links['menu-browse-library_books--authors:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Books & Authors',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_books--authors:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_featured-and-popular-topics:<front>
  $menu_links['menu-browse-library_featured-and-popular-topics:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Featured and Popular Topics',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_featured-and-popular-topics:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_home-schooling-resources:<front>
  $menu_links['menu-browse-library_home-schooling-resources:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Home Schooling Resources',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_home-schooling-resources:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_journals--publications:<front>
  $menu_links['menu-browse-library_journals--publications:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Journals & Publications',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_journals--publications:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_mises-daily:<front>
  $menu_links['menu-browse-library_mises-daily:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Mises Daily',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_mises-daily:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_mises-view:<front>
  $menu_links['menu-browse-library_mises-view:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Mises View',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_mises-view:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_quarterly-journal-of-austrian-economics:<front>
  $menu_links['menu-browse-library_quarterly-journal-of-austrian-economics:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Quarterly Journal of Austrian Economics',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_quarterly-journal-of-austrian-economics:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_resources-for-the-economist:<front>
  $menu_links['menu-browse-library_resources-for-the-economist:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Resources for the Economist',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_resources-for-the-economist:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_the-free-market:<front>
  $menu_links['menu-browse-library_the-free-market:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'The Free Market',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_the-free-market:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-library_what-is-the-austrian-school-of-economics:<front>
  $menu_links['menu-browse-library_what-is-the-austrian-school-of-economics:<front>'] = array(
    'menu_name' => 'menu-browse-library',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'What is the Austrian School of Economics?',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-browse-library_what-is-the-austrian-school-of-economics:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Audio & Video');
  t('Books & Authors');
  t('Featured and Popular Topics');
  t('Home Schooling Resources');
  t('Journals & Publications');
  t('Mises Daily');
  t('Mises View');
  t('Quarterly Journal of Austrian Economics');
  t('Resources for the Economist');
  t('The Free Market');
  t('What is the Austrian School of Economics?');


  return $menu_links;
}
