<?php
/**
 * @file
 * Code for the Solr Search feature.
 */

include_once 'mises_solr_search.features.inc';

/** 
 * On each page load, ensure Solr is read-only if in use on devmises.org
 * except when used from http://master-content.mises.devmises.org.
 *
 * Since the solr index is remote and will allow any instance of this site to modify index contents,
 * this function is in place to prevent multiple dev sites from indexing content and potentially
 * causing unexpected content to appear in Solr search results.
 *
 * Solr environments are only updated if a change has to be made.
 */
function _mises_solr_search_manage_solr_write_access() {
  if (!function_exists('apachesolr_load_all_environments')) {
    return;
  }

  // Do nothing if this is mises.org or is the Blackmesh site:
  if (stripos($_SERVER['HTTP_HOST'], 'dev.mises.org.468elmp01.blackmesh.com') !== FALSE ||
      stripos($_SERVER['HTTP_HOST'], 'mises.org') !== FALSE) {
    return;
  } 


  // Load the Solr environment(s) (Please note that this function handles caches.):
  $solr_environments = apachesolr_load_all_environments();

  // For all solr environments, ensure read-only mode is enabled:
  foreach ($solr_environments as $environment) {
    // Don't modify this environment if read-only mode is already set:
    if (isset($environment['conf']['apachesolr_read_only']) && $environment['conf']['apachesolr_read_only'] === '1') {
      continue;
    }

    $environment['conf']['apachesolr_read_only'] = '1';

    // Emulate form values on Apache Solr configuration to minimize unintended results:
    unset($environment['conf']['apachesolr_index_last']);
    unset($environment['conf']['apachesolr_index_updated']);
    unset($environment['conf']['apachesolr_index_optimized']);

    apachesolr_environment_save($environment);
  }
}

/**
 * Implements hook_init().
 *
 * Enforcer devmises solr rules with each page load:
 */
function mises_solr_search_init() {
  _mises_solr_search_manage_solr_write_access();
}

/**
 * Implements hook_form_alter().
 *
 * To avoid confusion, modifies the Solr settings form to
 * make it clear that "Read only" access to the index is being enforced:
 */
function mises_solr_search_form_apachesolr_environment_edit_form_alter(&$form, &$form_state, $form_id) {
  // Do nothing if this is mises.org or is the Blackmesh site:
  if (stripos($_SERVER['HTTP_HOST'], 'dev.mises.org.468elmp01.blackmesh.com') === TURE ||
      stripos($_SERVER['HTTP_HOST'], 'mises.org') === TRUE) {
    return;
  }

  // Disable modification of the "Index write access" field:
  $form['conf']['apachesolr_read_only']['#disabled'] = TRUE;
  $form['conf']['apachesolr_read_only']['#description'] .= '<br /><br />' . '<span style="color:#f00;">' .
    t('Attention: This field is disabled on devmises.org via mises_solr_search.module to prevent multiple dev sites from unintentionally ' .
      'modifying the remotely hosted Solr index.') . '<br />' .
    t('All devmises.org sites must remain in read-only mode, except for master-content.mises.devmises.org.') . '</span>';
  
}
