<?php
/**
 * @file
 * mises_award_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mises_award_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Alford',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0ab299e3-981c-4ce4-beb3-d8837fd7b547',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Mises University Examination - Finalist',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0ed13784-eb7f-4cdf-a2af-ee94ba28a873',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Eddy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1e4a750d-a488-4673-91f2-935fea587a36',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Groseclose',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '32e85015-4731-4e0c-8923-0b68790079ea',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Rothbard',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4b6e10b5-f473-4e36-8671-aa84b638fd23',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'French',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4e9349dc-eb4f-40c9-863e-8ff664e16ea3',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Mises University Examination - Passed with Honors',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '87417e31-dba8-43b1-a8e0-3b8951fb00e9',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Entrepreneur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a844ac78-6b3b-44cc-a525-81c9b394d74e',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Koether',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b738ca9e-7613-44d7-b286-74e7de83a9f1',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Fertig',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c300ed3f-b0a6-4fed-ae42-e23d2281e8ac',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Rothbard Graduate Seminar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd94c2fa8-8698-49b9-b895-1fa85d84775c',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Mises University Examination - Passed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e29b6e22-6cd1-4847-8306-c1511cff38cc',
    'vocabulary_machine_name' => 'award_type',
  );
  $terms[] = array(
    'name' => 'Schlarbaum',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f7379413-ce4c-4fe5-9422-d5ea1ad92b83',
    'vocabulary_machine_name' => 'award_type',
  );
  return $terms;
}
