<?php
/**
 * @file
 * topics.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function topics_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'The Entrepreneur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '0570dfd6-2dc1-4ce3-93a6-17636c323d89',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'U.S. Economy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 17,
    'uuid' => '0957c364-8634-4a29-845a-c14af00feb72',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Media and Culture',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '09a9abdf-57ca-4870-b70f-6e9a64b4002b',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'World History',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 20,
    'uuid' => '1aaea5a5-0dea-4779-803c-d66ca6f22d2c',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Free Markets',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '261dfa02-296b-4587-af65-65543b35f65b',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'The Environment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '2dc22b1f-1206-4f9f-8446-626e826a79ec',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Big Government',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '54a32efb-bfd3-413d-8871-650217faeedd',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Money and Banks',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => '5d09f5c3-8d54-4f6c-ad46-622c4140a8ab',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Global Economy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '66084146-967f-4c6a-bab7-046c518c6780',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'War and Foreign Policy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 19,
    'uuid' => '67a17b72-7f03-4d21-8b21-24bb9f441f97',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'The Police State',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 15,
    'uuid' => '6f5f03b3-da31-4851-9e29-95041444a7fa',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'The Fed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '7d3d73c4-0623-4c2e-bddf-dd2ebe093b34',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Biographies',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '8b3d43d0-9c3c-4ef9-be8a-204e59152591',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Corporate Welfare',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'aecb837f-5ecb-44b1-869d-01199378590b',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Booms and Busts',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'c2287daa-7292-48a3-ac79-0ffd374c692c',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Taxes and Spending',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 16,
    'uuid' => 'c48bee67-765c-45cf-b0f1-5af4e16813f5',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'c582925c-857a-4fe0-8e9a-7303bd8ff986',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Financial Markets',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'd03f595a-3d07-4016-80de-97fa474ddb0b',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => 'db6d28d0-03a5-4e21-9700-52b5e82a2d0c',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'U.S. History',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 18,
    'uuid' => 'dc16f9de-cefc-443a-b0ff-f0f57ace3b2b',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Legal System',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => 'ebeacf76-55a1-4ff3-b0ea-82410582b5df',
    'vocabulary_machine_name' => 'currents_trends',
    'metatags' => array(),
  );
  return $terms;
}
