<?php
/**
 * @file
 * menu_footer_topics.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function menu_footer_topics_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-topics_big-government:taxonomy/term/20
  $menu_links['menu-topics_big-government:taxonomy/term/20'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/20',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Big Government',
    'options' => array(
      'attributes' => array(
        'title' => 'Big Government',
      ),
      'identifier' => 'menu-topics_big-government:taxonomy/term/20',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_biographies:taxonomy/term/194
  $menu_links['menu-topics_biographies:taxonomy/term/194'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/194',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Biographies',
    'options' => array(
      'attributes' => array(
        'title' => 'Biographies',
      ),
      'identifier' => 'menu-topics_biographies:taxonomy/term/194',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_booms-and-busts:taxonomy/term/21
  $menu_links['menu-topics_booms-and-busts:taxonomy/term/21'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/21',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Booms and Busts',
    'options' => array(
      'attributes' => array(
        'title' => 'Booms and Busts',
      ),
      'identifier' => 'menu-topics_booms-and-busts:taxonomy/term/21',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_corporate-welfare:taxonomy/term/22
  $menu_links['menu-topics_corporate-welfare:taxonomy/term/22'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/22',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Corporate Welfare',
    'options' => array(
      'attributes' => array(
        'title' => 'Corporate Welfare',
      ),
      'identifier' => 'menu-topics_corporate-welfare:taxonomy/term/22',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_education:taxonomy/term/28
  $menu_links['menu-topics_education:taxonomy/term/28'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/28',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Education',
    'options' => array(
      'attributes' => array(
        'title' => 'Education',
      ),
      'identifier' => 'menu-topics_education:taxonomy/term/28',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_financial-markets:taxonomy/term/195
  $menu_links['menu-topics_financial-markets:taxonomy/term/195'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/195',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Financial Markets',
    'options' => array(
      'attributes' => array(
        'title' => 'Financial Markets',
      ),
      'identifier' => 'menu-topics_financial-markets:taxonomy/term/195',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_free-markets:taxonomy/term/25
  $menu_links['menu-topics_free-markets:taxonomy/term/25'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/25',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Free Markets',
    'options' => array(
      'attributes' => array(
        'title' => 'Free Markets',
      ),
      'identifier' => 'menu-topics_free-markets:taxonomy/term/25',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_global-economy:taxonomy/term/26
  $menu_links['menu-topics_global-economy:taxonomy/term/26'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/26',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Global Economy',
    'options' => array(
      'attributes' => array(
        'title' => 'Global Economy',
      ),
      'identifier' => 'menu-topics_global-economy:taxonomy/term/26',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_health:taxonomy/term/27
  $menu_links['menu-topics_health:taxonomy/term/27'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/27',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Health',
    'options' => array(
      'attributes' => array(
        'title' => 'Health',
      ),
      'identifier' => 'menu-topics_health:taxonomy/term/27',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_legal-system:taxonomy/term/197
  $menu_links['menu-topics_legal-system:taxonomy/term/197'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/197',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Legal System',
    'options' => array(
      'attributes' => array(
        'title' => 'Legal System',
      ),
      'identifier' => 'menu-topics_legal-system:taxonomy/term/197',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_media-and-culture:taxonomy/term/29
  $menu_links['menu-topics_media-and-culture:taxonomy/term/29'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/29',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Media and Culture',
    'options' => array(
      'attributes' => array(
        'title' => 'Media and Culture',
      ),
      'identifier' => 'menu-topics_media-and-culture:taxonomy/term/29',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 13,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_money-and-banks:taxonomy/term/30
  $menu_links['menu-topics_money-and-banks:taxonomy/term/30'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/30',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Money and Banks',
    'options' => array(
      'attributes' => array(
        'title' => 'Money and Banks',
      ),
      'identifier' => 'menu-topics_money-and-banks:taxonomy/term/30',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 14,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_taxes-and-spending:taxonomy/term/32
  $menu_links['menu-topics_taxes-and-spending:taxonomy/term/32'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/32',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Taxes and Spending',
    'options' => array(
      'attributes' => array(
        'title' => 'Taxes and Spending',
      ),
      'identifier' => 'menu-topics_taxes-and-spending:taxonomy/term/32',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 16,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_the-entrepreneur:taxonomy/term/23
  $menu_links['menu-topics_the-entrepreneur:taxonomy/term/23'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/23',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'The Entrepreneur',
    'options' => array(
      'attributes' => array(
        'title' => 'The Entrepreneur',
      ),
      'identifier' => 'menu-topics_the-entrepreneur:taxonomy/term/23',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_the-environment:taxonomy/term/193
  $menu_links['menu-topics_the-environment:taxonomy/term/193'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/193',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'The Environment',
    'options' => array(
      'attributes' => array(
        'title' => 'The Environment',
      ),
      'identifier' => 'menu-topics_the-environment:taxonomy/term/193',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_the-fed:taxonomy/term/24
  $menu_links['menu-topics_the-fed:taxonomy/term/24'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/24',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'The Fed',
    'options' => array(
      'attributes' => array(
        'title' => 'The Fed',
      ),
      'identifier' => 'menu-topics_the-fed:taxonomy/term/24',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_the-police-state:taxonomy/term/31
  $menu_links['menu-topics_the-police-state:taxonomy/term/31'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/31',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'The Police State',
    'options' => array(
      'attributes' => array(
        'title' => 'The Police State',
      ),
      'identifier' => 'menu-topics_the-police-state:taxonomy/term/31',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 15,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_us-economy:taxonomy/term/33
  $menu_links['menu-topics_us-economy:taxonomy/term/33'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/33',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'U.S. Economy',
    'options' => array(
      'attributes' => array(
        'title' => 'U.S. Economy',
      ),
      'identifier' => 'menu-topics_us-economy:taxonomy/term/33',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 17,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_us-history:taxonomy/term/196
  $menu_links['menu-topics_us-history:taxonomy/term/196'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/196',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'U.S. History',
    'options' => array(
      'attributes' => array(
        'title' => 'U.S. History',
      ),
      'identifier' => 'menu-topics_us-history:taxonomy/term/196',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 18,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_war-and-foreign-policy:taxonomy/term/34
  $menu_links['menu-topics_war-and-foreign-policy:taxonomy/term/34'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/34',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'War and Foreign Policy',
    'options' => array(
      'attributes' => array(
        'title' => 'War and Foreign Policy',
      ),
      'identifier' => 'menu-topics_war-and-foreign-policy:taxonomy/term/34',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 19,
    'customized' => 0,
  );
  // Exported menu link: menu-topics_world-history:taxonomy/term/192
  $menu_links['menu-topics_world-history:taxonomy/term/192'] = array(
    'menu_name' => 'menu-topics',
    'link_path' => 'taxonomy/term/192',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'World History',
    'options' => array(
      'attributes' => array(
        'title' => 'World History',
      ),
      'identifier' => 'menu-topics_world-history:taxonomy/term/192',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 20,
    'customized' => 0,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Big Government');
  t('Biographies');
  t('Booms and Busts');
  t('Corporate Welfare');
  t('Education');
  t('Financial Markets');
  t('Free Markets');
  t('Global Economy');
  t('Health');
  t('Legal System');
  t('Media and Culture');
  t('Money and Banks');
  t('Taxes and Spending');
  t('The Entrepreneur');
  t('The Environment');
  t('The Fed');
  t('The Police State');
  t('U.S. Economy');
  t('U.S. History');
  t('War and Foreign Policy');
  t('World History');


  return $menu_links;
}
