<?php

/**
 * Implements hook_form_alter().
 */
function mises_solr_ct_submit_disable_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('solr_online_text_chapter_node_form', 'solr_online_text_page_node_form'))) {
    // Disable form submission of Solr-related content type node edit forms and display a related message.
    drupal_set_message('This content is used by Drupal Solr and cannot be changed.');
    $js = '
      (function ($) {
        $("#solr-online-text-chapter-node-form #edit-actions, #solr-online-text-page-node-form #edit-actions").hide();
        $("#solr-online-text-chapter-node-form, #solr-online-text-page-node-form").submit(function (e) {
          e.preventDefault();
        });
      })(jQuery);
    ';
    $form['#submit'][] = '_mises_solr_ct_submit_disable_form_submit';
    drupal_add_js($js, array('type' => 'inline', 'scope' => 'footer', 'cache' => TRUE));
  }
}

function _mises_solr_ct_submit_disable_form_submit($form_id, &$form_state) {
  drupal_set_message($form_id);
  if (in_array($form_id, array('solr_online_text_chapter_node_form', 'solr_online_text_page_node_form'))) {
    // Disable form submission of Solr-related content type node edit forms and display a related message.
    drupal_set_message('This content is used by Drupal Solr and cannot be changed.');
    return FALSE;
  }
}


