<?php
/**
 * @file
 * footer_about_menu.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function footer_about_menu_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-about-the-mises-institute_contact-us:<front>
  $menu_links['menu-about-the-mises-institute_contact-us:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Contact Us',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_contact-us:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_faculty--staff:<front>
  $menu_links['menu-about-the-mises-institute_faculty--staff:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Faculty & Staff',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_faculty--staff:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_fellowship--independent-research:<front>
  $menu_links['menu-about-the-mises-institute_fellowship--independent-research:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Fellowship & Independent Research',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_fellowship--independent-research:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_finances-and-board:<front>
  $menu_links['menu-about-the-mises-institute_finances-and-board:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Finances and Board',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_finances-and-board:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_mises-bookstore:<front>
  $menu_links['menu-about-the-mises-institute_mises-bookstore:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Mises Bookstore',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_mises-bookstore:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_mises-events:<front>
  $menu_links['menu-about-the-mises-institute_mises-events:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Mises Events',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_mises-events:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_mises-publications:<front>
  $menu_links['menu-about-the-mises-institute_mises-publications:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Mises Publications',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_mises-publications:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_online-learning:<front>
  $menu_links['menu-about-the-mises-institute_online-learning:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Online Learning',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_online-learning:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_press-room:<front>
  $menu_links['menu-about-the-mises-institute_press-room:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Press Room',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_press-room:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_resource-library:<front>
  $menu_links['menu-about-the-mises-institute_resource-library:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Resource Library',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_resource-library:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_subscribe-to-email-lists:<front>
  $menu_links['menu-about-the-mises-institute_subscribe-to-email-lists:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Subscribe to Email Lists',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_subscribe-to-email-lists:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_support-mises:<front>
  $menu_links['menu-about-the-mises-institute_support-mises:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Support Mises',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_support-mises:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
  );
  // Exported menu link: menu-about-the-mises-institute_what-is-the-mises-institute:<front>
  $menu_links['menu-about-the-mises-institute_what-is-the-mises-institute:<front>'] = array(
    'menu_name' => 'menu-about-the-mises-institute',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'What is the Mises Institute?',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about-the-mises-institute_what-is-the-mises-institute:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Contact Us');
  t('Faculty & Staff');
  t('Fellowship & Independent Research');
  t('Finances and Board');
  t('Mises Bookstore');
  t('Mises Events');
  t('Mises Publications');
  t('Online Learning');
  t('Press Room');
  t('Resource Library');
  t('Subscribe to Email Lists');
  t('Support Mises');
  t('What is the Mises Institute?');


  return $menu_links;
}
