<?php
/**
 * @file
 * austrian_school.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function austrian_school_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Capital and Interest Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '1f1c5a30-fee2-4bd4-9b0c-5b02733e0655',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Monopoly and Competition',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => '3fc84f20-4b35-44e1-a5ba-8486790b4669',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Other Schools of Thought',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '46716d8a-e4f9-4e85-be42-cba59626a259',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Business Cycles',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5ac02c0e-93f6-48ab-9347-58e4786b8243',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Gold Standard',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '5c35329f-0ffc-4960-8498-43afb76ab0d1',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Monetary Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '610c6512-c639-4254-8c02-f0052a0e1949',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Money and Banking',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '72f94b27-ebac-4a6a-8d12-d9074d3ae681',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Prices',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 16,
    'uuid' => '77555035-2d70-4ea2-9362-45a8a3cd5899',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Interventionism',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '7dcaf211-5446-4c71-b3d6-7fb07c687eda',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Philosophy and Methodology',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '8e1ae438-9e9d-4d80-bcb5-06a8328ebe81',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Praxeology',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 15,
    'uuid' => '8e3191ac-9cf5-400d-8034-e797492baa95',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Fiscal Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '8fd344e3-0621-4e4f-9bb0-892cbd788cae',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'History of the Austrian School of Economics',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'a686b729-3bf3-4595-bd9a-8a9709850eda',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Calculation and Knowledge',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'abc24295-ad5d-4423-8fe6-e143c538b28e',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Subjectivism',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 18,
    'uuid' => 'b67bac7c-5ba7-4ccc-82f2-2a3403180038',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Factors of Production',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'c0140c84-5cc5-4570-8138-fe90287d5b59',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Value and Exchange',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 17,
    'uuid' => 'c3d2f92c-720f-4681-bdff-24853b412c01',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Political Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => 'e847c6db-7582-4645-bafc-c1e1e48fb522',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Entrepreneurship',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'fcd4970c-47d4-4511-ba2b-600ceaacf1a0',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  return $terms;
}
