<?php
/**
 * @file
 * menu_footer_austrian_school.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function menu_footer_austrian_school_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-austrian-school_business-cycles:taxonomy/term/35
  $menu_links['menu-austrian-school_business-cycles:taxonomy/term/35'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/35',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Business Cycles',
    'options' => array(
      'attributes' => array(
        'title' => 'Business Cycles',
      ),
      'identifier' => 'menu-austrian-school_business-cycles:taxonomy/term/35',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_calculation-and-knowledge:taxonomy/term/36
  $menu_links['menu-austrian-school_calculation-and-knowledge:taxonomy/term/36'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/36',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Calculation and Knowledge',
    'options' => array(
      'attributes' => array(
        'title' => 'Calculation and Knowledge',
      ),
      'identifier' => 'menu-austrian-school_calculation-and-knowledge:taxonomy/term/36',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_capital-and-interest-theory:taxonomy/term/37
  $menu_links['menu-austrian-school_capital-and-interest-theory:taxonomy/term/37'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/37',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Capital and Interest Theory',
    'options' => array(
      'attributes' => array(
        'title' => 'Capital and Interest Theory',
      ),
      'identifier' => 'menu-austrian-school_capital-and-interest-theory:taxonomy/term/37',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_entrepreneurship:taxonomy/term/39
  $menu_links['menu-austrian-school_entrepreneurship:taxonomy/term/39'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/39',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Entrepreneurship',
    'options' => array(
      'attributes' => array(
        'title' => 'Entrepreneurship',
      ),
      'identifier' => 'menu-austrian-school_entrepreneurship:taxonomy/term/39',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_factors-of-production:taxonomy/term/38
  $menu_links['menu-austrian-school_factors-of-production:taxonomy/term/38'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/38',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Factors of Production',
    'options' => array(
      'attributes' => array(
        'title' => 'Factors of Production',
      ),
      'identifier' => 'menu-austrian-school_factors-of-production:taxonomy/term/38',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_fiscal-theory:taxonomy/term/191
  $menu_links['menu-austrian-school_fiscal-theory:taxonomy/term/191'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/191',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Fiscal Theory',
    'options' => array(
      'attributes' => array(
        'title' => 'Fiscal Theory',
      ),
      'identifier' => 'menu-austrian-school_fiscal-theory:taxonomy/term/191',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_gold-standard:taxonomy/term/40
  $menu_links['menu-austrian-school_gold-standard:taxonomy/term/40'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/40',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Gold Standard',
    'options' => array(
      'attributes' => array(
        'title' => 'Gold Standard',
      ),
      'identifier' => 'menu-austrian-school_gold-standard:taxonomy/term/40',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_history-of-the-austrian-school-of-economics:taxonomy/term/41
  $menu_links['menu-austrian-school_history-of-the-austrian-school-of-economics:taxonomy/term/41'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/41',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'History of the Austrian School of Economics',
    'options' => array(
      'attributes' => array(
        'title' => 'History of the Austrian School of Economics',
      ),
      'identifier' => 'menu-austrian-school_history-of-the-austrian-school-of-economics:taxonomy/term/41',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_interventionism:taxonomy/term/42
  $menu_links['menu-austrian-school_interventionism:taxonomy/term/42'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/42',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Interventionism',
    'options' => array(
      'attributes' => array(
        'title' => 'Interventionism',
      ),
      'identifier' => 'menu-austrian-school_interventionism:taxonomy/term/42',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_monetary-theory:taxonomy/term/44
  $menu_links['menu-austrian-school_monetary-theory:taxonomy/term/44'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/44',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Monetary Theory',
    'options' => array(
      'attributes' => array(
        'title' => 'Monetary Theory',
      ),
      'identifier' => 'menu-austrian-school_monetary-theory:taxonomy/term/44',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_money-and-banking:taxonomy/term/43
  $menu_links['menu-austrian-school_money-and-banking:taxonomy/term/43'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/43',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Money and Banking',
    'options' => array(
      'attributes' => array(
        'title' => 'Money and Banking',
      ),
      'identifier' => 'menu-austrian-school_money-and-banking:taxonomy/term/43',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_monopoly-and-competition:taxonomy/term/45
  $menu_links['menu-austrian-school_monopoly-and-competition:taxonomy/term/45'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/45',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Monopoly and Competition',
    'options' => array(
      'attributes' => array(
        'title' => 'Monopoly and Competition',
      ),
      'identifier' => 'menu-austrian-school_monopoly-and-competition:taxonomy/term/45',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_other-schools-of-thought:taxonomy/term/189
  $menu_links['menu-austrian-school_other-schools-of-thought:taxonomy/term/189'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/189',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Other Schools of Thought',
    'options' => array(
      'attributes' => array(
        'title' => 'Other Schools of Thought',
      ),
      'identifier' => 'menu-austrian-school_other-schools-of-thought:taxonomy/term/189',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_philosophy-and-methodology:taxonomy/term/46
  $menu_links['menu-austrian-school_philosophy-and-methodology:taxonomy/term/46'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/46',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Philosophy and Methodology',
    'options' => array(
      'attributes' => array(
        'title' => 'Philosophy and Methodology',
      ),
      'identifier' => 'menu-austrian-school_philosophy-and-methodology:taxonomy/term/46',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 13,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_political-theory:taxonomy/term/47
  $menu_links['menu-austrian-school_political-theory:taxonomy/term/47'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/47',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Political Theory',
    'options' => array(
      'attributes' => array(
        'title' => 'Political Theory',
      ),
      'identifier' => 'menu-austrian-school_political-theory:taxonomy/term/47',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 14,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_praxeology:taxonomy/term/190
  $menu_links['menu-austrian-school_praxeology:taxonomy/term/190'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/190',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Praxeology',
    'options' => array(
      'attributes' => array(
        'title' => 'Praxeology',
      ),
      'identifier' => 'menu-austrian-school_praxeology:taxonomy/term/190',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 15,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_prices:taxonomy/term/48
  $menu_links['menu-austrian-school_prices:taxonomy/term/48'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/48',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Prices',
    'options' => array(
      'attributes' => array(
        'title' => 'Prices',
      ),
      'identifier' => 'menu-austrian-school_prices:taxonomy/term/48',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 16,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_subjectivism:taxonomy/term/50
  $menu_links['menu-austrian-school_subjectivism:taxonomy/term/50'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/50',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Subjectivism',
    'options' => array(
      'attributes' => array(
        'title' => 'Subjectivism',
      ),
      'identifier' => 'menu-austrian-school_subjectivism:taxonomy/term/50',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 18,
    'customized' => 0,
  );
  // Exported menu link: menu-austrian-school_value-and-exchange:taxonomy/term/49
  $menu_links['menu-austrian-school_value-and-exchange:taxonomy/term/49'] = array(
    'menu_name' => 'menu-austrian-school',
    'link_path' => 'taxonomy/term/49',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Value and Exchange',
    'options' => array(
      'attributes' => array(
        'title' => 'Value and Exchange',
      ),
      'identifier' => 'menu-austrian-school_value-and-exchange:taxonomy/term/49',
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 17,
    'customized' => 0,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Business Cycles');
  t('Calculation and Knowledge');
  t('Capital and Interest Theory');
  t('Entrepreneurship');
  t('Factors of Production');
  t('Fiscal Theory');
  t('Gold Standard');
  t('History of the Austrian School of Economics');
  t('Interventionism');
  t('Monetary Theory');
  t('Money and Banking');
  t('Monopoly and Competition');
  t('Other Schools of Thought');
  t('Philosophy and Methodology');
  t('Political Theory');
  t('Praxeology');
  t('Prices');
  t('Subjectivism');
  t('Value and Exchange');


  return $menu_links;
}
