<?php
/**
 * @file
 * mises_entity.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mises_entity_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Corporate Welfare',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0112496c-0e8e-4f46-8970-c4100fed54a2',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Joseph Sobran',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '055dcfc0-ab59-4325-ae8a-237440bc479e',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'History and Biography',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '07d1f356-7de4-48b4-9f4f-087a95b7d118',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Business Cycles',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0b2ea497-ff08-41a5-a335-bfa59e3e3ab9',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Entrepreneurship',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0b63b804-4925-47c2-8a88-30ab9b6767ee',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Gold Standard',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '165f7652-1811-4f77-b533-368365e1ab28',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '166e35a9-e967-429d-be97-0a14e15f85a5',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Value and Exchange',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1938f4cf-2c99-4eeb-b0bc-1b3ed9bfb8d9',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Robert Higgs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1c39baa1-ca66-439e-8da8-420c46672a8f',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Joseph Salerno',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1e7dcaa0-87c1-449b-a830-dd5d0598e527',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(
      'und' => array(
        0 => array(
          'value' => 'Joseph Salerno is academic vice president of the Mises Institute, professor of economics at Pace University, and editor of the Quarterly Journal of Austrian Economics. He has been interviewed in the Austrian Economics Newsletter and on Mises.org. Send him mail.',
          'format' => NULL,
          'safe_value' => 'Joseph Salerno is academic vice president of the Mises Institute, professor of economics at Pace University, and editor of the Quarterly Journal of Austrian Economics. He has been interviewed in the Austrian Economics Newsletter and on Mises.org. Send him mail.',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'The Police State',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2212820c-c9de-436c-ae15-28e9a5811046',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'War and Foreign Policy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2bde3e8e-8436-4b2a-b9f8-1714a0eb85a2',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Judge Andrew Napolitano',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2c112207-6d88-42d9-8231-a0cbc9196b4f',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'U.S. Economy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2e614d0c-7d49-4d79-8c9b-28489933c78e',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'B. T. Donleavy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '31a4acff-e18b-48cb-b3bc-4f9b2a4dbbc1',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(
      'und' => array(
        0 => array(
          'value' => 'B.T. Donleavy is a foreign-exchange specialist in New York City. He has worked at several Fortune 500 companies and he advised Michael Moore on the effects of loose monetary policy for the film Capitalism: A Love Story. ',
          'format' => NULL,
          'safe_value' => 'B.T. Donleavy is a foreign-exchange specialist in New York City. He has worked at several Fortune 500 companies and he advised Michael Moore on the effects of loose monetary policy for the film Capitalism: A Love Story. ',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'The Fed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3d5cc20a-57d5-496c-a243-2bfb21541b33',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Ralph Raico',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '42f5616a-c961-47b1-b8af-85a8a691f3d2',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Robert F. Mulligan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '46a6c333-9ea5-4286-b64b-d5494d3d08d3',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Monopoly and Competition',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '47ed7cd5-2467-495b-8f05-491be80f98dd',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Peter G. Klein',
    'description' => 'Peter G. Klein is the author of The Capitalist & the Entrepreneur: Essays on Organizations & Markets. Peter Klein is the Executive Director and Carl Menger Research Fellow at the Mises Institute. Klein teaches in the Mises Academy. He blogs at Organizations and Markets. See his webpage. Send him mail.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4908c25c-52be-4704-9467-be88215cbeb1',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Interventionism',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '490f0e71-f64e-43ca-906a-e2ef2e9452e9',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Monetary Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4c3a4d14-3feb-4ebb-b1b5-a80c777bec36',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Calculation and Knowledge',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4d5e8c22-e0b6-4894-861b-d219bb253f81',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Entrepreneurs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4dcc2073-707e-4c14-9596-3a9702a0d5ec',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '520d9c86-1515-4d57-bd23-2d9b33b2f64e',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Ron Paul',
    'description' => 'Dr. Ron Paul is a former member of Congress and a Distinguished Counselor to the Mises Institute.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5c82a209-e21c-4c32-9fc9-560afa6ac692',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Capital Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5d496ed7-af25-47a3-afd8-cdde43d83c3a',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Media and Culture',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '61e4f8d6-ee6c-4efd-8bfc-8614b52bbb70',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'David Gordon',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6d294ce0-0255-4e98-9220-b74f378833e1',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Political Theory',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '712e31bd-cc29-41cc-94b7-f97e75c8c0dc',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Capital and Production',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '767a45b5-57e9-4900-a676-a865266a74f6',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Money and Banks',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '77f19351-d45c-4022-92b1-5c2850aa920c',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Danny Sanchez',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7a5dce81-de7a-41b8-99f8-803251f6d003',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Big Government',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '82167d5d-6441-4787-b600-9a558f43f487',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Henry G. Manne',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '85915bb2-5042-4e2f-989c-c553c434703d',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Mark Thornton',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8b867a69-aaf9-4ebd-9bc4-73d5db3b0f5c',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Taxes and Spending',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8e62ea4e-d929-4954-b2f0-fd4f99246f46',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Prices',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9187ffd2-3b54-41b5-891a-e7832ed6129a',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Money and Banking',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9a2229ca-93ef-4239-969d-44054b495872',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Frank Fetter',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ab9ab3f9-572c-47b0-8e85-64e46998d50c',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Booms and Busts',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b6472a41-b697-4cc9-b475-365dd1349861',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'Murray N. Rothbard',
    'description' => 'Murray N. Rothbard (1926–1995) was dean of the Austrian School. He was an economist, economic historian, and libertarian political philosopher.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b70ca337-58a5-43e7-89ad-face8e4dbbd1',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Subjectivism',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bd600fa2-b8ad-4eed-8398-307f1bb2ef60',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Free Markets',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c24ef84a-2222-4563-9d54-04d6d45f65d8',
    'vocabulary_machine_name' => 'currents_trends',
  );
  $terms[] = array(
    'name' => 'George Reismann',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cadc3d5d-2695-4e42-854b-bfd410278b9e',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Ludwig von Mises',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ddeae5c4-fb29-45dc-9ada-abf845e67960',
    'vocabulary_machine_name' => 'authors',
    'field_biography' => array(),
  );
  $terms[] = array(
    'name' => 'Philosophy and Methodology',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e5efa091-d27c-4589-9ef4-e6c918dfa627',
    'vocabulary_machine_name' => 'the_austrian_school_of_economics',
  );
  $terms[] = array(
    'name' => 'Global Economy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f6403786-27b2-4682-b81a-8e9a85367136',
    'vocabulary_machine_name' => 'currents_trends',
  );
  return $terms;
}
