<?php

/**
 * Implements hook_apachesolr_query_alter().
 */
/* function mises_solr_featured_nodes_apachesolr_query_alter(DrupalSolrQueryInterface $query) {
  $queue = nodequeue_load_queue_by_name('top_results_list');
  // $queue_nodes = nodequeue_load_nodes($queue->qid, FALSE, 0, 0);
  $subqueue = nodequeue_load_subqueue($queue->qid);
  $sqid = $subqueue->sqid;

  $query->addParams(
    array(
      'bq' => _nodequeue_solr_qid_key() . ':' . $sqid . '^21',
      'facet.field' => _nodequeue_solr_qid_key(),
    )
  );

  drupal_set_message('<pre>' . print_r(apachesolr_entity_fields(), 1) . '</pre>');
} */

/**
 * Implements hook_apachesolr_search_page_alter().
 */
function mises_solr_featured_nodes_apachesolr_search_page_alter(&$build, $search_page) {
  return;
}
