<?php

/**
 */
function mises_itunes_rss_changes_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name != 'mises_itunes_rss_feeds' || $display_id != 'itunes_feed') {
    return;
  }

  // Update the description to match the taxonomy contextual filter:
  drupal_set_message('<pre>' . print_r($view, 1) . '</pre>');
  $tid = arg(1);
  if (is_numeric($tid)) {
    $term = taxonomy_term_load($tid);
    if (isset($term->description)) {
      $descr = $term->description;
      $view->display_handler
        ->options['style_options']['channel']['core']['views_rss_core']['description'] = $descr;
    }
  }
}
